const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
  .get('/landing', (req, res) => res.render('pages/landing'))
  .get('/cascade', (req, res) => res.render('pages/cascade'))
  .get('/test', (req, res) => res.render('pages/test'))
  .get('/videos', (req, res) => res.render('pages/videos'))
  .get('/services', (req, res) => res.render('pages/services'))
  .get('/who-we-help', (req, res) => res.render('pages/who-we-help'))
  .get('/seo', (req, res) => res.render('pages/seo'))
  .get('/advertisement', (req, res) => res.render('pages/advertisement'))
  .get('/ppc', (req, res) => res.render('pages/ppc'))
  .get('/directory-listings', (req, res) => res.render('pages/directory-listings'))
  .get('/social-media-marketing', (req, res) => res.render('pages/social-media-marketing'))
  .get('/content-marketing', (req, res) => res.render('pages/content-marketing'))
  .get('/web-design', (req, res) => res.render('pages/web-design'))
 .get('/contact', (req, res) => res.render('pages/contact'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
